baseURL = "https://buhocms.org"
title = "BuhoCMS - A local CMS for Hugo static sites"
languageCode = "en-us"
disableKinds = ['taxonomy', 'term']

[params]
  description = "BuhoCMS is a free and open source local CMS for Hugo static sites"
  source = "https://github.com/iakmds/buhocms-website"
  favicon = "https://raw.githubusercontent.com/iakmds/buhocms/main/.github/icon.svg"
  version = "0.4.0"

